version: "3.3"
services:
  web:
    image: ngudkov/kubernetes-demo:1.6
    ports:
      - 8080:8080
    environment:
      - spring.activemq.broker-url=tcp://activemq:61616
    links:
      - activemq
  activemq:
    image: rmohr/activemq:5.15.9
    ports:
      - 61616:61616
      - 8161:8161
    expose:
      - 61616